In [6]:
import numpy as np
from PIL import Image

In [20]:
img = Image.open('10 x 10 Image.png')
arr = np.array(img) 
arr

array([[ 0,  0,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 0,  0,  0,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  0, 15, 16, 17, 18, 19, 20, 21, 22],
       [ 0, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48, 49, 50, 51],
       [52, 53, 54, 55, 56, 57, 58, 59, 60, 61],
       [62, 63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80, 81],
       [82, 83, 84, 85, 86, 87, 88, 89, 90,  0]], dtype=uint8)

In [13]:
arr=arr.T
print(arr)

[[ 0  0  0  0 32 42 52 62 72 82]
 [ 0  0  0 23 33 43 53 63 73 83]
 [ 0  0 15 24 34 44 54 64 74 84]
 [ 1  8 16 25 35 45 55 65 75 85]
 [ 2  9 17 26 36 46 56 66 76 86]
 [ 3 10 18 27 37 47 57 67 77 87]
 [ 4 11 19 28 38 48 58 68 78 88]
 [ 5 12 20 29 39 49 59 69 79 89]
 [ 6 13 21 30 40 50 60 70 80 90]
 [ 7 14 22 31 41 51 61 71 81  0]]


In [49]:
import numpy as np
from numpy.linalg import norm
v = [32, 42, 52]
vector = np.array(v)
l2=norm(vector)